theme              : jekyll-theme-cayman
title              : Thomas Maltesen
description        : PhD student
url                : https://mcl868.github.io/


author:
  name             : "Thomas Maltesen"
  avatar           : 
  bio              : 
  location         : "Copenhagen, Denmark"
  employer         :
  googlescholar    : 
  email            :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "mcl868"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  wordpress        : 