theme       : jekyll-theme-slate
title       : Welcome to my homepage
description : Updated last time 2019-11-29
name        : Thomas Maltesen
url         : https://mcl868.github.io/
version     : v0.0.1
date_format : "%B %-d, %Y"

